data/urls.py
from django.urls import path
from . import views
app_name='data'
urlpatterns=[
    path('',views.html_show,name='tang'),
]

index/urls.py
from django.urls import path
from . import views

app_name='index'
urlpatterns = [
    path('historys/', views.History.as_view()),
    path('main/',views.newdata_show,name='index'),
    path('history/',views.history_show,name='history'),
    # 在iframe中镶嵌的地图
    path('baidu/',views.baiDu_api,name='baidu'),
    path('map/', views.map, name='map'),
    path('instrument/',views.instrument,name='instrument'),
    path('instrument_data/', views.instrument_data),
    path('chart/', views.chart_show,name='chart'),

]

users/urls.py
from django.urls import path
from . import views
app_name='users'
urlpatterns = [
    # v1/user/sms 发送短信的地址和个人主页的地址相似，但是这里用sms，即username不能是sms（视图函数会进错）
    # path('<str:username>',views.UserViews.as_view()),
    # path('<str:username>/avatar',views.users_views),
    # path('<str:username>/password',views.change_password),

    # 试用
    path('sms',views.sms_view),
    path('register/',views.register_show,name='register'),
    path('login/', views.login_show, name='login'),
    path('loginout/', views.loginout_view, name='loginout'),
]

waterQualityMonitoringSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from wtoken import views as wtoken_views
app_name='main'

urlpatterns = [
    path('',include('data.urls')),
    path('admin/', admin.site.urls,name='admin'),

    # 试用
    # path('v1/users/', include('usersss.urls')),

    # 进一步试用
    path('tokens', wtoken_views.tokens),
    path('users/', include('users.urls')),
    path('users', user_views.UserViews.as_view()),
    path('index/', include('index.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/index/baiDu_api.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>定位</title>

    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

    <style type="text/css">
    html{height:100%}
    body{height:100%;margin:0px;padding:0px}
    #container{height:100%}
    </style>

    <script type="text/javascript" src="https://api.map.baidu.com/api?v=1.0&&type=webgl&ak=iYGTussQeVvOS6tKpcSi1lePKt2WBvrs"></script>

</head>

<body>

{#地图需要一个HTML元素作为容器，这样才能展现到页面上。这里我们创建了一个div元素。#}
<div id="container"></div>

    <script>
        {# 成都东软学院坐标 103.60277805625807--30.89450785626509#}

    {#创建一个map 地图对象#}
    var map = new BMapGL.Map("container");

    {#创建一个point 点对象#}
    var point = new BMapGL.Point(103.60277805625807,30.89450785626509);

    {#设置中心点和缩放级别#}
    map.centerAndZoom(point, 15);

    {#缩放功能#}
    map.enableScrollWheelZoom(true);

    {#展示标记点#}
    var marker=new BMapGL.Marker(point);
    map.addOverlay(marker);

    {#展示信息框#}
        var opts={
        {#信息窗口宽度#}
        width:250,
        {#信息窗口高度#}
        height:150,
            };

        var content="<h4 style='margin: 0 0 5px 0;padding: 0.2em 0'>水质监测器</h4>"+
"<img style='float: right;margin: 4px' id='imgdemo' src='{% static 'images/水质监测器.png' %}' width='139' height='104' title='水质监测器' alt='水质监测器'>"+
"<p style='margin: 0;line-height: 1.5;font-size: 13px;text-indent: 2em'><a href='http://127.0.0.1:8000/user/reg'>Vibe项目团队所设计的水质监测器。</a></p>"+"</div>";

    {#创建信息窗口对象#}
    var infoWindow=new BMapGL.InfoWindow(content,opts);

    {#打开信息窗口#}
    map.openInfoWindow(infoWindow,point);

    </script>
</body>
</html>

templates/index/baocuo.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Admin Dashboard Template">
    <meta name="keywords" content="admin,dashboard">
    <meta name="author" content="stacks">
    <!-- The above 6 meta tags *must* come first in the head;any other head content must come *after* these tags -->
    <!-- Title -->
    <title>报错数据</title>
    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,700,800&display=swap" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/perfectscroll/perfect-scrollbar.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/DataTables/datatables.min.css' %}" rel="stylesheet">
    <!-- Theme Styles -->
    <link href="{% static 'css/main.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
	
	<style >

        {#下方没有该数据#}
		{#@font-face {#}
		{#  font-family: 'icomoon';#}
		{#  src:  url('fonts/icomoon.eot?vtvr13');#}
		{#  src:  url('fonts/icomoon.eot?vtvr13#iefix') format('embedded-opentype'),#}
		{#    url('fonts/icomoon.ttf?vtvr13') format('truetype'),#}
		{#    url('fonts/icomoon.woff?vtvr13') format('woff'),#}
		{#    url('fonts/icomoon.svg?vtvr13#icomoon') format('svg');#}
		{#  font-weight: normal;#}
		{#  font-style: normal;#}
		{#  font-display: block;#}
		{# }#}

		span1{
			font-family: 'icomoon';
			font-size:15px;
		}
	</style>
</head>

<body>
    <div class="page-container">
        <div class="page-header">
            <nav class="navbar navbar-expand-lg d-flex justify-content-between">
                <div class="" id="navbarNav">
                    <ul class="navbar-nav" id="leftNav">
                        <li class="nav-item">
                            <a class="nav-link" id="sidebar-toggle" href="#"><i data-feather="arrow-left"></i></a>
                    </ul>
                </div>
                <div class="logo">
                    <a class="navbar-brand" href="index.html"></a>
                </div>
                <div class="" id="headerNav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link profile-dropdown" href="#" id="profileDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><img src="../../assets/images/avatars/profile-image.png" alt=""></a>
                            <div class="dropdown-menu dropdown-menu-end profile-drop-menu" aria-labelledby="profileDropDown">
								<a class="dropdown-item" href="{% url 'usersss:loginout' %}"><i data-feather="log-out"></i>退出登录</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="page-sidebar">
            <ul class="list-unstyled accordion-menu">
                <li class="sidebar-title">主菜单</li>
                <li><a href="{% url 'index:index' %}"><span1>&nbsp</span1>实时数据</a></li>
                <li><a href="{% url 'index:baocuo' %}"><span1>&nbsp</span1></i>历史数据</a></li>
            </ul>
        </div>
        <div class="page-content">
            <div class="main-wrapper">
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">报错数据</h5>
                                <table id="zero-conf" class="display" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>PH(溶液酸碱度)</th>
                                            <th>TDS(可溶性物体浓度)</th>
                                            <th>TU(溶液浊度)</th>
                                            <th>位置</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Tiger Nixon</td>
                                            <td>System Architect</td>
                                            <td>Edinburgh</td>
                                            <td>61</td>
                                        </tr>
                                        <tr>
                                            <td>Garrett Winters</td>
                                            <td>Accountant</td>
                                            <td>Tokyo</td>
                                            <td>63</td>
                                        </tr>
                                        <tr>
                                            <td>Ashton Cox</td>
                                            <td>Junior Technical Author</td>
                                            <td>San Francisco</td>
                                            <td>66</td>
                                        </tr>
                                    </tbody>
                                    
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Javascripts -->
    <script src="{% static 'plugins/jquery/jquery-3.4.1.min.js' %}../../assets/"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="{% static 'plugins/perfectscroll/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/datatables.min.js' %}"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
    <script src="{% static 'js/pages/datatables.js' %}"></script>
</body>

</html> 

templates/index/error.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Admin Dashboard Template">
    <meta name="keywords" content="admin,dashboard">
    <meta name="author" content="stacks">
    <!-- The above 6 meta tags *must* come first in the head;any other head content must come *after* these tags -->
    <!-- Title -->
    <title>报错数据</title>
    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,700,800&display=swap" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome/css/all.min.css'%}" rel="stylesheet">
    <link href="{% static 'plugins/perfectscroll/perfect-scrollbar.css'%}" rel="stylesheet">
    <link href="{% static 'plugins/DataTables/datatables.min.css'%}" rel="stylesheet">
    <!-- Theme Styles -->
    <link href="{% static 'css/main.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/custom.css'%}" rel="stylesheet">
	

</head>

<body>


    <div class="page-container">
        <div class="page-header">
            <nav class="navbar navbar-expand-lg d-flex justify-content-between">
                <div class="" id="navbarNav">
                    <ul class="navbar-nav" i    d="leftNav">
                        <li class="nav-item">
                            <a class="nav-link" id="sidebar-toggle" href="#"><i data-feather="arrow-left"></i></a>
                        
                    </ul>
                </div>
                <div class="logo">
                    <a class="navbar-brand" href="index.html"></a>
                </div>
                <div class="" id="headerNav">
                    <ul class="navbar-nav">
                        
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link profile-dropdown" href="#" id="profileDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><img src="{% static 'images/avatars/profile-image.png' %}" alt=""></a>
                            <div class="dropdown-menu dropdown-menu-end profile-drop-menu" aria-labelledby="profileDropDown">
								<a class="dropdown-item" href="{% url 'usersss:loginout' %}"><i data-feather="log-out"></i>退出登录</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="page-sidebar">
            <ul class="list-unstyled accordion-menu">
                <li class="sidebar-title">主菜单</li>
                <li><a href="{% url 'index:index' %}"><i data-feather="list"></i>实时数据</a></li>
                <li><a href="{% url 'index:history' %}"><i data-feather="pie-chart"></i>历史数据</a></li>
                <li><a href="{% url 'index:error' %}"><i data-feather="edit"></i>报错数据</a></li>
               
            </ul>
        </div>
        <div class="page-content">
            <div class="main-wrapper">

                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">报错数据</h5>
                                <table id="zero-conf" class="display" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>PH(溶液酸碱度)</th>
                                            <th>TDS(可溶性物体浓度)</th>
                                            <th>TU(溶液浊度)</th>
                                            <th>位置</th>
                                            <th>时间</th>
                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Tiger Nixon</td>
                                            <td>System Architect</td>
                                            <td>Edinburgh</td>
                                            <td>61</td>
                                           
                                        </tr>
                                        <tr>
                                            <td>Garrett Winters</td>
                                            <td>Accountant</td>
                                            <td>Tokyo</td>
                                            <td>63</td>
                                           
                                        </tr>
                                        <tr>
                                            <td>Ashton Cox</td>
                                            <td>Junior Technical Author</td>
                                            <td>San Francisco</td>
                                            <td>66</td>
                                            
                                        </tr>
                                    </tbody>
                                    
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                
                
                
            </div>
        </div>
    </div>
    <!-- Javascripts -->
    <script src="{% static 'plugins/jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="{% static 'plugins/perfectscroll/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/datatables.min.js' %}"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
    <script src="{% static 'js/pages/datatables.js' %}"></script>
    <script>
setTimeout(function() {
        window.location.reload()
}, 5000);
    </script>
</body>

</html> 

templates/index/instrument.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Admin Dashboard Template">
    <meta name="keywords" content="admin,dashboard">
    <meta name="author" content="stacks">
    <title>设备管理</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,700,800&display=swap" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/perfectscroll/perfect-scrollbar.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/apexcharts/apexcharts.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <style>
        span1 {
            font-family: 'icomoon';
            font-size: 15px;
        }
        .ph_style {
            color: red;
        }
        .ftu_style {
            color: red;
        }
        .tds_style {
            color: red;
        }
        .tem_style{
            color:red;
                 }
    </style>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>

<body>

    <div class='loader'>
        <div class='spinner-grow text-primary' role='status'>
            <span class='sr-only'>Loading...</span>
        </div>
    </div>
    <div class="page-container">
        <div class="page-header">
            <nav class="navbar navbar-expand-lg d-flex justify-content-between">
                <div class="" id="navbarNav">
                    <ul class="navbar-nav" id="leftNav">
                        <li class="nav-item"><a class="nav-link" id="sidebar-toggle" href="#"><i data-feather="arrow-left"></i></a></li>
                    </ul>
                </div>
                <div class="logo">
                    <a class="navbar-brand" href="/index/instrument"></a>
                </div>
                <div class="" id="headerNav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link profile-dropdown" href="#" id="profileDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><img src="{% static 'images/avatars/profile-image.png' %}" alt=""></a>
                            <div class="dropdown-menu dropdown-menu-end profile-drop-menu" aria-labelledby="profileDropDown">
                                    <a class="dropdown-item" href="{% url 'users:loginout' %}"><i data-feather="log-out"></i>退出登录</a>
                                    <a class="dropdown-item" href="/admin"><i data-feather="log-out"></i>管理员登陆</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
            <div class="page-sidebar">
                <ul class="list-unstyled accordion-menu">
                    <li class="sidebar-title">全部设备</li>
                    <li><a href="#"><i data-feather="layers"></i>设备1</a></li>
                    <li><a href="#"><i data-feather="layers"></i>设备2</a></li>
                    <li><a href="#"><i data-feather="layers"></i>设备3</a></li>
                </ul>
            </div>
            <div class="page-content">
                <div class="main-wrapper">
                    <div class="row">
                        <div class="col-md-6 col-xl-3">
                            <div class="card stat-widget">
                                <div class="card-body ph">
                                    <h5 class="card-title">酸碱度 PH</h5>
                                    <!-- PH显示 -->
                                    <h2 class="PH ph_style" id="ph">{{ PH }}</h2>
                                    <div class="progress">
                                        <div class="progress-bar bg-info progress-bar-striped" role="progressbar" style="width: 100%"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-3">
                            <!--浊度显示  -->
                            <div class="card stat-widget">
                                <div class="card-body">
                                    <h5 class="card-title">浊度 TU</h5>
                                    <h2 class="FTU ftu_style" id="tu">{{ TU }}</h2>
                                    <div class="progress">
                                        <div class="progress-bar bg-success progress-bar-striped" role="progressbar" style="width: 100%"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-3">
                            <!-- TDS显示 -->
                            <div class="card stat-widget">
                                <div class="card-body">
                                    <h5 class="card-title">固体溶解度 TDS</h5>
                                    <h2 class="TDS tds_style" id="tds">{{ TDS }}</h2>
                                    <div class="progress">
                                        <div class="progress-bar bg-danger progress-bar-striped" role="progressbar" style="width:100%"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xl-3">
                            <div class="card stat-widget">
                                <div class="card-body">
                                    <h5 class="card-title">温度 TEM</h5>
                                    <h2 class="TEM tem_style" id="tem">{{ TEM }}</h2>
                                    <div class="progress">
                                        <div class="progress-bar bg-primary progress-bar-striped" role="progressbar" style="width: 100%"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="cod-md-2 col-xl-12">
                            <div class="card stat-widget">
                                <div class="card-body">
                                    <div class="card-title" id="button" align="center" onclick="window.location.href='/index/main';">点击了解更多</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <!-- Javascripts -->
    <script src="{% static 'plugins/jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="{% static 'plugins/perfectscroll/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'plugins/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
    <script src="{% static 'js/pages/dashboard.js' %}"></script>

    <script>
        var ph1 = $('.PH')
        var ph = $('.PH').text()
        if (ph > 8 || ph < 6) {
            ph1.addClass("ph_style")
        } else {
            ph1.removeClass("ph_style")
        }
    </script>
    <script>
        var ftu1 = $('.FTU')
        var ftu = $('.FTU').text()
        if (ftu > 500 || ftu < 100) {
            ftu1.addClass("ftu_style")
        } else {
            ftu1.removeClass("ftu_style")
        }
    </script>
    <script>
        var tds1 = $('.TDS')
        var tds = $('.TDS').text()
        if (tds > 1000) {
            tds1.addClass("tds_style")
        } else {
            tds1.removeClass("tds_style")
        }
    </script>
    <script>
        var tds1 = $('.TEM')
        var tds = $('.TEM').text()
        if (tds < 25|| tds>35 ) {
            tds1.addClass("tem_style")
        } else {
            tds1.removeClass("tem_style")
        }
    </script>

        <script>
        var obj1 = document.getElementById('ph');
        var obj2 = document.getElementById('tu');
        var obj3 = document.getElementById('tds');
        var obj4 = document.getElementById('tem');

        setInterval(function() {
        $.ajax({
            type:"GET",
            url:"http://127.0.0.1:8000/index/instrument_data",
            async:false,
            success:function (result) {
                if (result['code']===200){
                    var ph=result['data']['ph'];
                    var tu=result['data']['tu'];
                    var tds=result['data']['tds'];
                    var tem=result['data']['tem'];
                    obj1.innerText = ph;
                    obj2.innerText = tu;
                    obj3.innerText = tds;
                    obj4.innerText = tem;

                    console.log(obj1.innerText);
                    console.log(obj2.innerText);
                    console.log(obj3.innerText);
                    console.log(obj4.innerText);
                }
           }
        });},3000);
        </script>

</body>
</html>

templates/index/map1.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    {#在服务器中防止嵌套被打断#}
    {#<style id="antiClickjack">body{display:none !important;}</style>#}
    {#<script>#}
    {#if (self === top) {#}
    {#var antiClickjack = document.getElementById("antiClickjack");#}
    {#antiClickjack.parentNode.removeChild(antiClickjack);#}
    {# } else { #}
    {#top.location = self.location;#}
    {# } #}
    {#</script>#}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Admin Dashboard Template">
    <meta name="keywords" content="admin,dashboard">
    <meta name="author" content="stacks">
    <title>水质监测器GPS</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,700,800&display=swap" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/perfectscroll/perfect-scrollbar.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <style >
            .ph_style{
				color: red;
			}
			.ftu_style{
				color: red;
			}
			.tds_style{
				color: red;
			}
		</style>

    {#百度api#}
            <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
    html{height:100%}
    body{height:100%;margin:0px;padding:0px}
    #container{height:100%}
    </style>
    <script type="text/javascript" src="https://api.map.baidu.com/api?v=1.0&&type=webgl&ak=iYGTussQeVvOS6tKpcSi1lePKt2WBvrs"></script>

</head>

<body>
    <div class="page-container">
        <div class="page-header">
            <nav class="navbar navbar-expand-lg d-flex justify-content-between">
                <div class="" id="navbarNav">
                    <ul class="navbar-nav" id="leftNav">
                        <li class="nav-item">
                            <a class="nav-link" id="sidebar-toggle" href="#"><i data-feather="arrow-left"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="logo">
                    <a class="navbar-brand" href="{% url 'index:index' %}"></a>
                </div>
                <div class="" id="headerNav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link profile-dropdown" href="#" id="profileDropDown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><img src="{% static 'images/avatars/profile-image.png' %}" alt=""></a>
                            <div class="dropdown-menu dropdown-menu-end profile-drop-menu" aria-labelledby="profileDropDown">
                                <a class="dropdown-item" href="{% url 'users:loginout'%}"><i data-feather="log-out"></i>退出登录</a>
                                <a class="dropdown-item" href="/admin"><i data-feather="log-out"></i>管理员登陆</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="page-sidebar">
            <ul class="list-unstyled accordion-menu">
                <li class="sidebar-title">主菜单</li>
                <li><a href="{% url 'index:index' %}"><i data-feather="list"></i>实时数据</a></li>
                <li><a href="{% url 'index:history' %}"><i data-feather="pie-chart"></i>历史数据</a></li>
                <li><a href="{% url 'index:map' %}"><i data-feather="edit"></i>设备位置</a></li>
                <li><a href="{% url 'index:instrument' %}"><i data-feather="inbox"></i>设备列表</a></li>
                <li><a href="{% url 'data:tang' %}"><i data-feather="home"></i>系统首页</a></li>
            </ul>
        </div>
        <?xml version="1.0" encoding="UTF-8"?>
        <div class="page-content">
            <div class="main-wrapper">
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <iframe src="{% url 'index:baidu' %}" name="map" width="100%" height="580px">
                            </iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Javascripts -->
    <script src="{% static 'plugins/jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="{% static 'plugins/perfectscroll/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'plugins/DataTables/datatables.min.js' %}"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
    <script src="{% static 'js/pages/datatables.js' %}"></script>
</body>
</html>

{#关于自定义api大小:#}
{#1.在settings中注释掉'django.middleware.clickjacking.XFrameOptionsMiddleware'#}
{#2.(推荐,有问题)安装第三方库,pip install django-cors-headers,在install_APP里面加corsheaders,然后再MIDDLEWARE_CLASSES里面添加"'corsheaders.middleware.CorsMiddleware',"到第一行#}
{#3.X_FRAME_OPTIONS='http://(想要不被iframe的网址)'#}