data/urls.py
from django.urls import path
from . import views
app_name='data'
urlpatterns=[
    path('',views.html_show,name='tang'),
]

index/urls.py
from django.urls import path
from . import views

app_name='index'
urlpatterns = [
    path('historys/', views.History.as_view()),
    path('main/',views.newdata_show,name='index'),
    path('history/',views.history_show,name='history'),
    # 在iframe中镶嵌的地图
    path('baidu/',views.baiDu_api,name='baidu'),
    path('map/', views.map, name='map'),
    path('instrument/',views.instrument,name='instrument'),
    path('instrument_data/', views.instrument_data),
    path('chart/', views.chart_show,name='chart'),

]

users/urls.py
from django.urls import path
from . import views
app_name='users'
urlpatterns = [
    # v1/user/sms 发送短信的地址和个人主页的地址相似，但是这里用sms，即username不能是sms（视图函数会进错）
    # path('<str:username>',views.UserViews.as_view()),
    # path('<str:username>/avatar',views.users_views),
    # path('<str:username>/password',views.change_password),

    # 试用
    path('sms',views.sms_view),
    path('register/',views.register_show,name='register'),
    path('login/', views.login_show, name='login'),
    path('loginout/', views.loginout_view, name='loginout'),
]

waterQualityMonitoringSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from wtoken import views as wtoken_views
app_name='main'

urlpatterns = [
    path('',include('data.urls')),
    path('admin/', admin.site.urls,name='admin'),

    # 试用
    # path('v1/users/', include('usersss.urls')),

    # 进一步试用
    path('tokens', wtoken_views.tokens),
    path('users/', include('users.urls')),
    path('users', user_views.UserViews.as_view()),
    path('index/', include('index.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
import random

# 随机的签名
def default_sign():
    signs=['每一个不曾起舞的日子,都是对生命的辜负.','给我们赦免的,是忏悔而不是牧师.','一旦被贴上标签,你就很难逃脱.','才貌出众的人多半在劫难逃.']
    return random.choice(signs)

# Create your models here.
class UserProfile(models.Model):
    # 在model中有primary_key=True属性的字段时，则model不会送id字段
    username=models.CharField(max_length=11,verbose_name='用户名',primary_key=True)
    password=models.CharField(max_length=32)
    phone=models.CharField(max_length=11)
    # models.ImageField(头像)和models.FileField（文件）相似（前者继承于后者）
    avatar=models.ImageField(upload_to='avatar',null=True)
    sign=models.CharField(max_length=50,verbose_name='个人签名',default=default_sign)
    created_time=models.DateTimeField(auto_now_add=True)
    updated_time=models.DateTimeField(auto_now=True)

    class Meta:
       db_table='users_info'

users/views.py
from django.shortcuts import render
from django.views import View
import json
from django.http import JsonResponse, HttpResponseRedirect
from django.core.cache import cache
from .models import UserProfile
import hashlib
import random
from django.conf import settings
from tools.sms import YunTongXin

# Create your views here.

class UserViews(View):
    # 注册 post
    # 注册所有的信息都传到该函数了
    def post(self,request):
        # 前端发送数据的类型是contentType:'application/json',如果用request.POST则取不到数据

        # 想要取到json数据:request.body
        json_str=request.body
        json_obj=json.loads(json_str)
        username=json_obj['username']
        password_1=json_obj['password_1']
        password_2=json_obj['password_2']
        phone=json_obj['phone']
        sms_num=json_obj['sms_num']

        # 参数基本检查

        # 两次密码是否正确
        if password_1!=password_2:
            result={'code':'10100','error':'两次输入的密码不同'}
            return JsonResponse(result)

        # 验证码比对
        old_code=cache.get('sms_%s'%(phone))
        if not old_code:
            result={'code':'10110','error':'验证码错误'}
            return JsonResponse(result)
        if int(sms_num)!=old_code:
            result={'code':'10111','error':'验证码错误'}
            return JsonResponse(result)

        # 用户名是否可用
        # get返回的是value(需要try一下)，filter返回的是编号（Q...set）（不用try）
        old_users=UserProfile.objects.filter(username=username)
        if old_users:
            result={'code':10101,'error':'该用户名已存在'}
            return JsonResponse(result)

        # 正确时
        # 向UserProfile插入数据（密码md5存储）
        p_m=hashlib.md5()
        # 将字符串转化为字节串
        p_m.update(password_1.encode())
        UserProfile.objects.create(username=username,password=p_m.hexdigest(),phone=phone)
        result={'code':200,'username':username,'data':{}}
        return JsonResponse(result)

# 用户注册
def register_show(request):
    return render(request, 'users/register.html')

# 用户登录
def login_show(request):
    return render(request, 'users/login.html')

# 发送短信（接受到电话号码 post）
def sms_view(request):
    if request.method!='POST':
        result={'code':10108,'error':'请使用POST表单提交'}
        return JsonResponse(result)
    json_str=request.body
    json_obj=json.loads(json_str)
    phone=json_obj['phone']
    # 生成随机码
    code=random.randint(1000,9999)
    print('phone',phone,'code',code)
    # 存储随机码（之前是redis，现在是django_redis（将redis和django的缓存结合））
    cache_key='sms_%s'%(phone)
    # 检查是否已经有发送的且没有过期的验证码
    old_code=cache.get(cache_key)
    if old_code:
        result={'code':10111,'error':'该验证码已经存在'}
        return JsonResponse(result)

    cache.set(cache_key,code,60)
    # 发送随机码->短信
    send_sms(phone,code)
    return JsonResponse({'code':200})

# 短信发送
def send_sms(phone,code):
    config={
        'accountSid':settings.ACCOUNTSID,
        'accountToken':settings.ACCOUNTTOKEN,
        'appId':settings.APPID,
        'templateId':settings.TEMPLATEID
    }
    yun=YunTongXin(**config)
    res=yun.run(phone,code)
    return res

# 退出登陆
def loginout_view(request):
    # session的删除
    # 1和2都是自己写的
    # 1.if 'username'  in request.session or 'uid' in request.session:
    # 2.if request.session.get('username') and request.session.get('uid'):
        # del request.session['username']
        # del request.session['uid']
    # cookie的删除
    # if 'remember' in request.POST:
        # if request.COOKIES.get('username') and request.COOKIES.get('uid'):
            # req_web=HttpResponseRedirect('/user/login')
            # req_web.delete_cookie('username')
            # req_web.delete_cookie('uid')
        # return HttpResponseRedirect('/user/login')
    # 删除session值：
    if 'username' in request.session:
        del request.session['username']
    if 'uid' in request.session:
        del  request.session['uid']
    # 删除Cookie：
    resp=HttpResponseRedirect('/index')
    if 'username' in request.COOKIES:
        resp.delete_cookie('username')
    if 'uid' in request.COOKIES:
        resp.delete_cookie('uid')
    return render(request,'users/login.html')

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Admin Dashboard Template">
    <meta name="keywords" content="admin,dashboard">
    <meta name="author" content="stacks">
    <title>水质监测系统-登陆</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,700,800&display=swap" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/perfectscroll/perfect-scrollbar.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
</head>

<body class="login-page">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-12 col-lg-4">
                <div class="card login-box-container">
                    <div class="card-body">
                        <div class="authent-logo"><img src={% static 'images/logo@2x.png' %}></div>
                        <div class="authent-text">
                        </div>
                        <div>

                            {#用户名#}
                            <div class="mb-3">
                                <div class="form-floating"><input type="text" class="form-control" name="username" id="username" placeholder="123456789"><label for="floatingInput">用户名</label></div>
                            </div>

                            {#手机号#}
{#                            <div class="mb-3">#}
{#							    <div class="form-floating"><input type="number" class="form-control" name="phone" id="floatingPassword1" placeholder="18718283811"><label for="floatingPassword">手机号</label></div>#}
{#							</div>#}

                            {#密码#}
                            <div class="mb-3">
                                <div class="form-floating"><input type="password" class="form-control" name="password" id="password" placeholder="Password"><label for="floatingPassword">密码</label></div>
                            </div>

                            {#记住登录#}
                            {#<div class="mb-3 form-check"><input type="checkbox" class="form-check-input" name="remember" id="exampleCheck1"><label class="form-check-label" for="exampleCheck1">Check me out</label></div>#}
                            {#<div class="d-grid">#}

                            {#登录按钮#}
                                <button type="submit" class="btn" style="background-color: #7888fc" onclick="login()">登陆</button>
							</div>
                        </div>

                        <div class="authent-reg">
                            <p>未注册<a href="{% url 'users:register' %}">创建一个账户</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	<div id="particles-js" style="display: flex;align-items: center;justify-content: center"></div>

    <!-- Javascripts -->
    <script src="{% static 'plugins/jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="{% static 'plugins/perfectscroll/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'js/main.min.js' %}"></script><script type="text/javascript"></script>
    <script src="{% static 'js/ccajax.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    {#跳转框#}
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

        {#万哥的ajax#}
{#        <script type="text/javascript">#}
            {#获取到4个输入框#}
{#            var usernameTag = $("input[name='username']");#}
{#            var passwordTag = $("input[name='password']");#}
{#            var phoneTag = $("input[name='phone']");#}
{#            var rememberTag = $("input[name='remember']");#}
{#		    $('.btn').click(function(){#}
		    {#.btn是提交按钮#}
{#            var username = usernameTag.val();#}
{#            var password = passwordTag.val();#}
{#            var phone = phoneTag.val();#}
{#            var remember1 = rememberTag.val();#}
{#             var remember2;#}
{#            (remember1 === 'on')?remember2=1:remember2=0;#}
{#            ccajax.post({#}
{#                'url': "/user/login/",#}
{#                'data': {#}
{#                    'username': username,#}
{#                    'password': password,#}
{#                    'phone': phone,#}
{#                    'remember': remember2#}
{#                },#}
{#                'success': function (res) {#}
{#                    console.log(res);#}
{#                    if(res['code'] === 200){#}
{#                        window.messageBox.showSuccess("登录成功！");#}
                        {#window.location.replace('http://10.69.23.12:40/index/')#}
{#                        window.location.replace('http://127.0.0.1:8000/index/')#}
{#                    }#}
{#                    },#}
{#                'failed': function () {#}
{#                }#}
{#            })#}
{#		})#}
{#	</script>#}

{#点击登录按钮时#}
<script>
	function login() {
	var username=$('#username').val();
	var password=$('#password').val();
	var post_data={'username':username,'password':password};
	$.ajax({
		type:'post',
		contentType:'application/json',
		dataType:'json',
		data:JSON.stringify(post_data),
		url:'http://127.0.0.1:8000/tokens',
		success:function (resule) {
			if (resule['code']===200){
				// set（存到本地数据）和get（获取本地中的数据）
				// dnblog_token和dnblog_user是老师在其他ajax中写死的，在这里不能改，但是在其他的情况下可以改
				window.localStorage.setItem('dnblog_token',resule.data.token);
				window.localStorage.setItem('dnblog_user',resule.username);

				{#alert('登陆成功');#}
                swal({
                            title:"登陆成功",
                            icon:"success",
                        });
				// 跳转到指定的网站 /之前是127.0.0.1:5000
                setTimeout(function () {
                    window.location.href='/index/main'
                }, 2000)
				// window.location.href='/index'
			}
			else {
				alert(resule.error)
			}
		}
	})
	}
</script>

</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Admin Dashboard Template">
    <meta name="keywords" content="admin,dashboard">
    <meta name="author" content="stacks">
    <title>水质监测系统-注册</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,700,800&display=swap" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/font-awesome/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/perfectscroll/perfect-scrollbar.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>


<body class="login-page">
    <div class='loader'>
        <div class='spinner-grow text-primary' role='status'>
            <span class='sr-only'>Loading...</span></div>
    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-12 col-lg-4">
                <div class="card login-box-container">
                    <div class="card-body">
                        {#首页头像#}
                        <div class="authent-logo"><img src="{% static 'images/logo@2x.png' %}" alt=""></div>
                        <div class="authent-text"></div>
                        {#form表单#}
                        {#<form action="{% url 'users:register' %}" method="post">#}
                        {#{% csrf_token %}#}

                            {#用户名#}
                            <div class="mb-3">
                                <div class="form-floating"><input type="text" name="username" class="form-control" id="username" placeholder="Fullname"><label for="floatingInput">用户名</label></div>
                            </div>

                            {#手机号#}
                            <div class="mb-3">
							    <div class="form-floating"><input type="number" name="phone" class="form-control" id="phone" placeholder="18718283811"><label for="floatingPassword">手机号</label></div>

                            {#获取验证码按钮#}
                                <input type="button" id="sms" onclick="sendSMS();settime(this)" value="免费获取验证码">
						<div class="clear"> </div>
							</div>

                            {#验证码#}
                            <div class="mb-3">
							    <div class="form-floating"><input type="sms_num" name="sms_num" class="form-control" id="sms_num" placeholder="1234"><label for="floatingPassword">验证码</label></div>
						<div class="clear"> </div>
							</div>

                            {#密码#}
                            <div class="mb-3">
                                <div class="form-floating"><input type="password" name="password_1" class="form-control" id="password_1" placeholder="Password"><label for="floatingPassword">密码</label></div>
                            </div>

                            {#确定密码#}
                            <div class="mb-3">
                                <div class="form-floating"><input type="password" name="password_2" class="form-control" id="password_2" placeholder="Confirm Password"><label for="floatingPassword">确认密码</label></div>
                            </div>

                            {#创建按钮#}
                            <div class="d-grid">
                                <button type="submit" class="btn" style="background-color: #7888fc" onclick="register()">创建</button>
                                {#<a href="{% url 'index:index' %} type='submit' class='btn btn-primary m-b-xs'">注册</a>#}
								</div>

                            {#</form>#}
                        <div class="authent-login">
                            <p>已有账户<a href="{% url 'users:login' %}">登录</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Javascripts -->
    <script src="{% static 'plugins/jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="{% static 'plugins/perfectscroll/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
    {#跳转框#}
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</body>

    <script>

        {#查看是否有查询字符串#}
        {#暂时没有用#}
        function getQueryVariable(variable)
        {
            var query = window.location.search.substring(1);
            var vars = query.split("&");
            for (var i=0;i<vars.length;i++) {
               var pair = vars[i].split("=");
               if(pair[0] == variable){return pair[1];}
            }
            return null;
        }

        {#计时器（60s）#}
	var countdown=60;
	function settime(obj) {
    	if (countdown == 0) {
        	obj.removeAttribute("removeAttribute");
        	obj.value="免费获取验证码";
			countdown = 60;
        	return;
    	} else {
        	obj.setAttribute("disabled", true);
        	obj.value="重新发送(" + countdown + ")";
        	countdown--;
    	}
		setTimeout(function() {
    		settime(obj) }
    	,1000)
	}

		{#按下注册按钮后#}
	    // post的ajex请求
		function register() {
		// 用jq来拿取数据
		var username=$('#username').val();
		var password_1=$('#password_1').val();
		var password_2=$('#password_2').val();
		var sms_num=$('#sms_num').val();
		var phone=$('#phone').val();
		// 用json串来发送数据
			var post_data={'username':username,'password_1':password_1,'password_2':password_2,'phone':phone,'sms_num':sms_num};
			$.ajax({
				type:'post',
				// 发送数据用json
				contentType:'application/json',
				// 返回数据也用json
				dataType:'json',
				// 现在post_data是json对象，发送的格式必须是json字符串(=json.dump)
				data:JSON.stringify(post_data),
				{#url:'http://127.0.0.1:8000/users',#}
                url:'http://127.0.0.1:8000/users',
				success:function (result) {
					if(result['code']===200)
					{
						// 弹一个框
						//alert('注册成功');

                        swal({
                            title:"注册成功",
                            icon:"success",
                        });
                        setTimeout(function () {
                    window.location.href='/users/login'
                }, 2000);
					}
					else {
						alert(result.error)
					}
				}
			})
		}

        {#发送短信#}
        function sendSMS() {
			var phone=$('#phone').val();
			var post_data={'phone':phone};
			$.ajax({
				type:'post',
				contentType: 'application/json',
				dataType: 'json',
				{#url:'http://127.0.0.1:8000/users/sms',#}
                url:'http://127.0.0.1:8000/users/sms',
				data:JSON.stringify(post_data),
				success:function (result) {
					if(result['code']===200){
						{#alert('短信已发送，请注意查收');#}
                        swal({
                            title:"短信已发送，请注意查收",
                            icon:"success",
                        });
					}else {
						{#alert(result.error)#}
                        swal({
                            title:"result.error",
                            icon:"error",
                        });
					}
				}
			})
		}
    </script>
</html>

templates/users/tang.html
<!DOCTYPE html>
<html lang="zxx">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>水质监测系统-Vibe</title>
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/LineIcons.css' %}">
    <link rel="stylesheet" href="{% static 'css/fakeLoader.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <div class="fakeLoader"></div>
    <nav class="navbar navbar-expand-md fixed-top">
        <div class="container"><a href="http://127.0.0.1:8000" class="navbar-brand"><img src="{% static 'images/vibe.png' %}" alt="" ></a><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                                                                                                                      aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">注册</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">登陆</a></li>
                    <li class="nav-item"><a class="nav-link" href="http://127.0.0.1:8000/admin">后台管理</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">关于我们</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="home-intro" id="home">
        <div class="container">
            <div class="row">
                <div class="col col-sm-12 col-md-6 col-12">
                    <div class="content">
                        <h5><span class="line"></span>WELCOME TO Water Quality Monitoring System </h5>
                        <br>
                        <br>
                        <br>
                        <h2>A SMART</h2>
                        <h2>SYSTEM</h2>
<!--                        <ul>-->
<!--                            <li><a href="" class="button">Get Started</a></li>-->
<!--                            <li><a href="" class="button2">Get Started</a></li>-->
<!--                        </ul>-->
                    </div>
                </div>
                <div class="col col-sm-12 col-md-6 col-12">
                    <div class="content-image"><img src="{% static 'images/water.jpg' %}" alt=""></div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom"><span>水质监测系统 By Vibe</span></div>
    <!-- script -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/fakeLoader.min.js' %}"></script>
    <script src="{% static 'js/jquery.filterizr.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/contact-form.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>